# Default values for integration-service-helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

serverSecret: PpKFhPKJY2efTsN9VkB7WNtYUhX9Utaa
apiKey: 94F5BA49-12B6-4E45-A487-BF91C442276D
network: main
explorer: https://explorer.iota.org/mainnet/transaction
iotaPermaNode: https://chrysalis-chronicle.iota.org/api/mainnet/
iotaHornetNode: https://chrysalis-nodes.iota.org:443
databaseUrl: mongodb://username:password@mongodb-service.default.svc.cluster.local:27017/integration-service-db?readPreference=primary&appname=integration-service-api&ssl=false

replicaCount: 1

image:
  repository: iotaledger/integration-services
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: ensuresec.solutions.iota.org
      # paths:
      #   - path: /
      #     pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 20
  targetMemoryUtilizationPercentage: 20

nodeSelector: {}

tolerations: []

affinity: {}
