apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-service-api
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: integration-service-api
  template:
    metadata:
      labels:
        app: integration-service-api
    spec:
      initContainers:
      - name: wait-for-hornet
        image: busybox:1.28
        args:
        - /bin/sh
        - -c
        - >
          set -x;
          until nslookup "hornet-tcp.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local";
          do 
          echo waiting for Hornet;
          sleep 2;
          done

      - name: wait-for-mongo
        image: busybox:1.28
        args:
        - /bin/sh
        - -c
        - >
          set -x;
          until nslookup "mongodb-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local";
          do 
          echo waiting for MongoDB;
          sleep 2;
          done

      - name: create-root-identity
        image: mastrogiovanni/e-commerce-tools:1.0.2
        command: ["node", "dist/index.js", "keygen"]
        env:
        - name: "SERVER_IDENTITY"
          value: "/config/server-identity.json"

#        - name: "API_VERSION"
#          valueFrom:
#            configMapKeyRef:
#              name: integration-service-api-config 
#              key: API_VERSION
        - name: "DATABASE_NAME"
          valueFrom:
            configMapKeyRef:
              name: integration-service-api-config 
              key: DATABASE_NAME
        - name: "NETWORK"
          valueFrom:
            configMapKeyRef:
              name: integration-service-api-config 
              key: NETWORK
#        - name: "EXPLORER"
#          valueFrom:
#            configMapKeyRef:
#              name: integration-service-api-config 
#              key: EXPLORER
#        - name: "IOTA_PERMA_NODE"
#          valueFrom:
#            configMapKeyRef:
#              name: integration-service-api-config 
#              key: IOTA_PERMA_NODE
        - name: "DATABASE_URL"
          valueFrom:
            configMapKeyRef:
              name: integration-service-api-config 
              key: DATABASE_URL
        - name: "IOTA_HORNET_NODE"
          valueFrom:
            configMapKeyRef:
              name: integration-service-api-config 
              key: IOTA_HORNET_NODE

        - name: "SERVER_SECRET"
          valueFrom:
            secretKeyRef:
              name: integration-service-api-secrets
              key: SERVER_SECRET

        volumeMounts:
        - mountPath: /config
          name: root-identity

      containers:
      - name: integration-service-api
        image: mastrogiovanni/e-commerce-tools:1.0.2
        command: ["node", "dist/index.js", "server"]
        resources:
          requests:
            memory: "100Mi"
            cpu: "250m"
          limits:
            memory: "250Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /info
            port: 3000
#            httpHeaders:
#            - name: Custom-Header
#              value: Awesome
#          initialDelaySeconds: 3
#          periodSeconds: 3
        env:
        - name: "SERVER_IDENTITY"
          value: "/config/server-identity.json"
        - name: "PORT"
          valueFrom:
            configMapKeyRef:
              name: integration-service-api-config 
              key: PORT

        - name: "API_VERSION"
          valueFrom:
            configMapKeyRef:
              name: integration-service-api-config 
              key: API_VERSION
        - name: "DATABASE_NAME"
          valueFrom:
            configMapKeyRef:
              name: integration-service-api-config 
              key: DATABASE_NAME
        - name: "NETWORK"
          valueFrom:
            configMapKeyRef:
              name: integration-service-api-config 
              key: NETWORK
        - name: "EXPLORER"
          valueFrom:
            configMapKeyRef:
              name: integration-service-api-config 
              key: EXPLORER
        - name: "IOTA_PERMA_NODE"
          valueFrom:
            configMapKeyRef:
              name: integration-service-api-config 
              key: IOTA_PERMA_NODE
        - name: "DATABASE_URL"
          valueFrom:
            configMapKeyRef:
              name: integration-service-api-config 
              key: DATABASE_URL
        - name: "IOTA_HORNET_NODE"
          valueFrom:
            configMapKeyRef:
              name: integration-service-api-config 
              key: IOTA_HORNET_NODE

        - name: "SERVER_SECRET"
          valueFrom:
            secretKeyRef:
              name: integration-service-api-secrets
              key: SERVER_SECRET
        - name: "API_KEY"
          valueFrom:
            secretKeyRef:
              name: integration-service-api-secrets
              key: API_KEY
        ports:
        - protocol: TCP
          containerPort: 3000
        volumeMounts:
        - mountPath: /data/db
          name: db
        - mountPath: /config
          name: root-identity
      volumes:
      - name: db
        persistentVolumeClaim:
          claimName: integration-service-pvc
      - name: root-identity
        persistentVolumeClaim:
          claimName: root-identity-pvc


