apiVersion: v1
kind: ConfigMap
metadata:
  name: init-mongo-cfg
data:
  mongo-init.js: |
    db.createUser(
      {
          user: "stocazzo",
          pwd: "stocazzo",
          roles: [
              {
                  role: "readWrite",
                  db: "e-commerce-audit-log"
              }
          ]
      }
    );
