apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "integration-service-helm-chart.fullname" . }}
data:
  PORT: "3000"
  API_VERSION: v1
  DATABASE_NAME: integration-service-db
  NETWORK:  {{ required "A valid .Values.network entry required!" .Values.network }}
  EXPLORER: {{ required "A valid .Values.explorer entry required!" .Values.explorer }}
  IOTA_PERMA_NODE: {{ required "A valid .Values.iotaPermaNode entry required!" .Values.iotaPermaNode }}
  IOTA_HORNET_NODE: {{ required "A valid .Values.iotaHornetNode entry required!" .Values.iotaHornetNode }}
  DATABASE_URL: {{ required "A valid .Values.databaseUrl entry required!" .Values.databaseUrl }}
