apiVersion: v1
kind: Secret
metadata:
  name: {{ include "integration-service-helm-chart.fullname" . }}
type: Opaque
data:
  SERVER_SECRET: {{ required "A valid .Values.serverSecret entry required!" .Values.serverSecret | b64enc }}
  API_KEY: {{ required "A valid .Values.apiKey entry required!" .Values.apiKey | b64enc }}

