apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "integration-service-helm-chart.fullname" . }}
data:
  PORT: "3000"
  API_VERSION: v1
  DATABASE_NAME: integration-service-db
  NETWORK: main
  EXPLORER: https://explorer.iota.org/mainnet/transaction
  IOTA_PERMA_NODE: https://chrysalis-chronicle.iota.org/api/mainnet/
  IOTA_HORNET_NODE: https://chrysalis-nodes.iota.org:443
  DATABASE_URL: mongodb://username:password@mongodb-service.default.svc.cluster.local:27017/integration-service-db?readPreference=primary&appname=integration-service-api&ssl=false
