apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "integration-service-helm-chart.fullname" . }}
spec:
  resources:
    requests:
      storage: 10Mi
  accessModes:
    - ReadWriteOnce
