apiVersion: v1
kind: Secret
metadata:
  name: {{ include "integration-service-helm-chart.fullname" . }}
type: Opaque
data:
  SERVER_SECRET: UHBLRmhQS0pZMmVmVHNOOVZrQjdXTnRZVWhYOVV0YWE=
  API_KEY: OTRGNUJBNDktMTJCNi00RTQ1LUE0ODctQkY5MUM0NDIyNzZE

