apiVersion: v1
kind: Service
metadata:
  name: {{ include "integration-service-helm-chart.fullname" . }}
  labels:
    {{- include "integration-service-helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      targetPort: http  
  selector:
    {{- include "integration-service-helm-chart.selectorLabels" . | nindent 4 }}
